* README.org

I am always interested in hearing of positions that would involve much of my
time being spent on one or more of these projects I already work on:

*** rebar3 / relx

[[https://github.com/erlang/rebar3][rebar3]] and
[[https://github.com/erlware/relx][relx]] are tools for Erlang development and
packaging. Each require continual maintenance and feature development to keep up
with new releases of Erlang and developers evolving needs.

*** OpenTelemetry

The [[https://opentelemetry.io][OpenTelemetry]] project involves both a
specification for distributed tracing, metrics and logging and the
implementation of the API and default SDK in various languages, including
Erlang/Elixir.

The Erlang/Elixir implementation is currently in beta with much work to do
before GA. In addition to managing the Erlang/Elixir SIG and working on the
implementations I'm involved in small part with the metrics and tracing spec
SIGs.

*** grpcbox

[[https://github.com/tsloughter/grpcbox][grpcbox]] is a client and server
implementation of [[http://grpc.io/][GRPC]] built on the Erlang HTTP/2
client/server [[https://github.com/joedevivo/chatterbox][chatterbox]].

Some future work is a refactoring of the client implementation and performance
improvements for chatterbox.

*** Erleans

[[https://github.com/erleans][Erleans]] is an Erlang version of
[[https://dotnet.github.io/orleans/][Orleans]]. It provides the [[http://research.microsoft.com/apps/pubs/default.aspx?id=210931][Virtual Actor
Model]] on top of
Erlang.

Erleans is still not mature but has the potential to provide a high level
distributed model for Erlang/Elixir developers to build systems for today's
highly dynamic cloud environments.
